spring:
  application:
    name: assetmybatis
  datasource:
    url: jdbc:sqlite:src/main/resources/mli-asset-management.db
    driver-class-name: org.sqlite.JDBC
  devtools:
    restart:
      enabled: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    persistAuthorization: true
    
server:
  port: 8091
  servlet:
    context-path: /practice5

mybatis:
  mapper-locations: classpath:/mapper/*.xml



