spring:
  application:
    name: discord
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;databaseName=discord;trustServerCertificate=true
    username: sa
    password: Wawi247525=
  devtools:
    restart:
      enabled: true
  security:
    user:
      password: wawi247525

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    persistAuthorization: true

server:
  port: 8088
  servlet:
    session:
      cookie:
        http-only: true

mybatis:
  mapper-locations: classpath:/mapper/*.xml
